import type { Role } from '@/types'

export interface MenuItem {
  id?: string
  icon?: string
  label?: string
  cat?: string
}

export type MenuMap = Record<Role, MenuItem[]>

export const MENUS: MenuMap = {
  engineer: [
    { id: 'home', icon: '🏠', label: 'Trang chủ / 홈' },
    { cat: '근태 / Chấm công' },
    { id: 'attendance', icon: '⏰', label: 'Chấm công / 출퇴근' },
    { id: 'leave', icon: '🏖️', label: 'Nghỉ phép / 휴가' },
    { cat: '현장 / Công trường' },
    { id: 'roll_call', icon: '✅', label: 'Điểm danh / 출석체크' },
    { id: 'tbm', icon: '🦺', label: 'An toàn TBM / 안전교육' },
    { id: 'safety', icon: '🛡️', label: 'An toàn / 안전점검' },
    { id: 'report', icon: '📋', label: 'Nhật ký / 일보' },
    { id: 'schedule', icon: '📅', label: 'Tiến độ / 공정' },
    { id: 'site_calendar', icon: '🗓️', label: 'Lịch trình / 일정관리' },
    { id: 'addwork', icon: '➕', label: 'Phát sinh / 추가항목' },
    { id: 'work_orders', icon: '📝', label: 'Chỉ thị / 작업지시서' },
    { cat: '자재·장비 / Vật tư' },
    { id: 'equipment', icon: '🚜', label: 'Thiết bị / 장비·공구' },
    { id: 'material', icon: '📦', label: 'Vật tư / 자재관리' },
    { cat: '재무 / Tài chính' },
    { id: 'billing_status', icon: '📑', label: 'Nghiệm thu TĐ / 기성현황' },
    { id: 'advance', icon: '💵', label: 'Tạm ứng / 전도금' },
    { cat: '기타 / Khác' },
    { id: 'quality', icon: '🔍', label: 'Kiem tra CL / 품질검사' },
    { id: 'defects', icon: '🔧', label: 'Bảo hành / 하자보수' },
    { id: 'legal_forms', icon: '📄', label: 'Biểu mẫu / 법정서식' },
    { id: 'daily_brief', icon: '📰', label: 'Tóm tắt / 일일브리핑' },
    { id: 'alert_center', icon: '🔔', label: 'Thông báo / 알림센터' },
    { id: 'history', icon: '📆', label: 'Lịch sử / 이력' },
    { id: 'gallery', icon: '📸', label: 'Ảnh CT / 현장사진' },
    { id: 'contacts', icon: '📞', label: 'Liên hệ / 비상연락처' },
  ],
  foreman: [
    { id: 'home', icon: '🏠', label: 'Trang chủ / 홈' },
    { cat: '근태 / Chấm công' },
    { id: 'attendance', icon: '⏰', label: 'Chấm công / 출퇴근' },
    { cat: '현장 / Công trường' },
    { id: 'roll_call', icon: '✅', label: 'Điểm danh / 출석체크' },
    { id: 'safety', icon: '🛡️', label: 'An toàn / 안전점검' },
    { id: 'report', icon: '📋', label: 'Nhật ký / 일보' },
    { cat: '자재·장비 / Vật tư' },
    { id: 'equipment', icon: '🚜', label: 'Thiết bị / 장비·공구' },
    { cat: '재무 / Tài chính' },
    { id: 'advance', icon: '💵', label: 'Tạm ứng / 전도금' },
    { cat: '기타 / Khác' },
    { id: 'quality', icon: '🔍', label: 'Kiem tra CL / 품질검사' },
    { id: 'defects', icon: '🔧', label: 'Bảo hành / 하자보수' },
    { id: 'gallery', icon: '📸', label: 'Ảnh CT / 현장사진' },
  ],
  driver: [
    { id: 'home', icon: '🏠', label: 'Trang chủ / 홈' },
    { cat: '근태 / Chấm công' },
    { id: 'attendance', icon: '⏰', label: 'Chấm công / 출퇴근' },
    { id: 'leave', icon: '🏖️', label: 'Nghỉ phép / 휴가' },
    { cat: '차량·재무 / Xe·Tài chính' },
    { id: 'vehicle', icon: '🚗', label: 'Xe cộ / 차량현황' },
    { id: 'driver_advance', icon: '💵', label: 'Chi phí xe / 차량비용' },
    { id: 'advance', icon: '💰', label: 'Yêu cầu TƯ / 전도금 신청' },
    { cat: '장비 / Thiết bị' },
    { id: 'equipment', icon: '🚜', label: 'Thiết bị / 장비·공구' },
    { cat: '기타 / Khác' },
    { id: 'gallery', icon: '📸', label: 'Ảnh CT / 현장사진' },
  ],
  qs: [
    { id: 'home', icon: '🏠', label: 'Trang chủ / 홈' },
    { cat: '근태 / Chấm công' },
    { id: 'attendance', icon: '⏰', label: 'Chấm công / 출퇴근' },
    { id: 'leave', icon: '🏖️', label: 'Nghỉ phép / 휴가' },
    { cat: '현장 / Công trường' },
    { id: 'gongmu', icon: '✅', label: 'Xác nhận NKC / 일보확인' },
    { id: 'schedule', icon: '📅', label: 'Tiến độ / 공정' },
    { id: 'site_calendar', icon: '🗓️', label: 'Lịch trình / 일정관리' },
    { id: 'addwork', icon: '➕', label: 'Phát sinh / 추가항목' },
    { cat: '자재·장비 / Vật tư' },
    { id: 'equipment', icon: '🚜', label: 'Thiết bị / 장비·공구' },
    { id: 'material', icon: '📦', label: 'Vật tư / 자재관리' },
    { cat: '재무·기성 / Tài chính' },
    { id: 'quantities', icon: '📐', label: 'Khối lượng HĐ / 계약물량' },
    { id: 'labor', icon: '👷', label: 'Đơn giá NC / 인건비' },
    { id: 'billing_all', icon: '🧾', label: 'Nghiệm thu / 기성관리' },
    { cat: '기타 / Khác' },
    { id: 'history', icon: '📆', label: 'Lịch sử / 이력' },
    { id: 'gallery', icon: '📸', label: 'Ảnh CT / 현장사진' },
  ],
  hr: [
    { id: 'home', icon: '🏠', label: 'Trang chủ / 홈' },
    { cat: '근태관리 / QL chấm công' },
    { id: 'attendance_all', icon: '⏰', label: 'Chấm công / 근태' },
    { id: 'leave_all', icon: '🏖️', label: 'Nghỉ phép / 휴가' },
    { id: 'salary', icon: '💰', label: 'Bảng lương / 급여' },
    { cat: '인력관리 / Nhân sự' },
    { id: 'workers', icon: '👷', label: 'Ho so CN / 인력 마스터' },
    { id: 'site_workers', icon: '👷', label: 'ĐK công nhân / 작업자 등록' },
    { id: 'roll_call', icon: '✅', label: 'Điểm danh / 출석체크' },
    { cat: '자재·장비 / Vật tư' },
    { id: 'equipment', icon: '🚜', label: 'Thiết bị / 장비·공구' },
    { id: 'material', icon: '📦', label: 'Vật tư / 자재관리' },
    { cat: '재무 / Tài chính' },
    { id: 'chongmu', icon: '📝', label: 'Duyệt TƯ / 전도금 승인' },
    { id: 'advance', icon: '💵', label: 'T.trạng TƯ / 전도금' },
    { cat: '관리 / Quản lý' },
    { id: 'gallery', icon: '📸', label: 'Ảnh CT / 현장사진' },
    { id: 'gps_verify', icon: '📍', label: 'GPS xác minh / GPS검증' },
    { id: 'login_photos', icon: '📷', label: 'Ảnh đăng nhập / 로그인사진' },
    { id: 'device_mgmt', icon: '📱', label: 'Thiết bị / 기기관리' },
    { id: 'sys_settings', icon: '⚙️', label: 'Cài đặt / 시스템 설정' },
  ],
  account: [
    { id: 'home', icon: '🏠', label: 'Trang chủ / 홈' },
    { id: 'multi_site', icon: '🌐', label: 'Tất cả CT / 전체 현장' },
    { cat: '급여·인사 / Lương·NS' },
    { id: 'salary', icon: '💰', label: 'Bảng lương / 급여' },
    { id: 'leave_all', icon: '🏖️', label: 'Nghỉ phép / 휴가' },
    { cat: '자재·장비 / Vật tư' },
    { id: 'equipment', icon: '🚜', label: 'Thiết bị / 장비·공구' },
    { id: 'material', icon: '📦', label: 'Vật tư / 자재관리' },
    { cat: '재무·기성 / Tài chính' },
    { id: 'expense_all', icon: '💸', label: 'Chi phí / 비용관리' },
    { id: 'chongmu', icon: '📝', label: 'Duyệt TƯ / 전도금 승인' },
    { id: 'advance', icon: '💵', label: 'Tạm ứng / 전도금' },
    { id: 'labor', icon: '👷', label: 'Đơn giá NC / 인건비' },
    { id: 'billing_all', icon: '🧾', label: 'Nghiệm thu / 기성관리' },
    { id: 'accounting', icon: '📊', label: 'Kế toán / 회계' },
    { id: 'monthly_close', icon: '📅', label: 'Chốt tháng / 월마감' },
    { cat: '기타 / Khác' },
    { id: 'vehicle', icon: '🚗', label: 'Xe cộ / 차량현황' },
    { id: 'annual_report', icon: '📈', label: 'Báo cáo năm / 연간보고' },
  ],
  director_f: [
    { id: 'home', icon: '🏠', label: 'Trang chủ / 홈' },
    { id: 'multi_site', icon: '🌐', label: 'Tất cả CT / 전체 현장' },
    { cat: '근태 / Chấm công' },
    { id: 'attendance', icon: '⏰', label: 'Chấm công / 출퇴근' },
    { id: 'leave_all', icon: '🏖️', label: 'Nghỉ phép / 휴가' },
    { cat: '현장 / Công trường' },
    { id: 'dashboard_all', icon: '🏛️', label: 'Tổng quan / 대시보드' },
    { id: 'schedule', icon: '📅', label: 'Tiến độ / 공정' },
    { id: 'site_calendar', icon: '🗓️', label: 'Lịch trình / 일정관리' },
    { cat: '인력관리 / Nhân sự' },
    { id: 'site_workers', icon: '👷', label: 'ĐK công nhân / 작업자 등록' },
    { id: 'roll_call', icon: '✅', label: 'Điểm danh / 출석체크' },
    { cat: '자재·장비 / Vật tư' },
    { id: 'equipment', icon: '🚜', label: 'Thiết bị / 장비·공구' },
    { id: 'material', icon: '📦', label: 'Vật tư / 자재관리' },
    { cat: '재무 / Tài chính' },
    { id: 'billing_status', icon: '📑', label: 'Nghiệm thu TĐ / 기성현황' },
    { id: 'advance', icon: '💵', label: 'Tạm ứng / 전도금' },
    { cat: '관리·기타 / Quản lý' },
    { id: 'defects', icon: '🔧', label: 'Bảo hành / 하자보수' },
    { id: 'vendors', icon: '🏢', label: 'NCC / 업체관리' },
    { id: 'doc_expiry', icon: '📄', label: 'Hết hạn / 문서만료' },
    { id: 'legal_forms', icon: '📄', label: 'Biểu mẫu / 법정서식' },
    { id: 'history', icon: '📆', label: 'Lịch sử / 이력' },
    { id: 'gallery', icon: '📸', label: 'Ảnh CT / 현장사진' },
    { id: 'sys_settings', icon: '⚙️', label: 'Cài đặt / 시스템 설정' },
  ],
  director_m: [
    { id: 'home', icon: '🏠', label: 'Trang chủ / 홈' },
    { id: 'multi_site', icon: '🌐', label: 'Tất cả CT / 전체 현장' },
    { cat: '근태 / Chấm công' },
    { id: 'attendance', icon: '⏰', label: 'Chấm công / 출퇴근' },
    { id: 'leave_all', icon: '🏖️', label: 'Nghỉ phép / 휴가' },
    { cat: '현장 / Công trường' },
    { id: 'dashboard_all', icon: '🏛️', label: 'Tổng quan / 대시보드' },
    { id: 'site_calendar', icon: '🗓️', label: 'Lịch trình / 일정관리' },
    { cat: '인력관리 / Nhân sự' },
    { id: 'workers', icon: '👷', label: 'Ho so CN / 인력 마스터' },
    { id: 'staff_all', icon: '👥', label: 'Nhân sự / 인력관리' },
    { id: 'roll_call', icon: '✅', label: 'Điểm danh / 출석체크' },
    { cat: '자재·장비 / Vật tư' },
    { id: 'equipment', icon: '🚜', label: 'Thiết bị / 장비·공구' },
    { id: 'material', icon: '📦', label: 'Vật tư / 자재관리' },
    { cat: '재무 / Tài chính' },
    { id: 'quantities', icon: '📐', label: 'Khối lượng HĐ / 계약물량' },
    { id: 'costana', icon: '💹', label: 'Dòng tiền / 자금현황' },
    { id: 'expense_all', icon: '💸', label: 'Chi phí / 비용관리' },
    { id: 'billing_all', icon: '🧾', label: 'Nghiệm thu / 기성관리' },
    { id: 'advance', icon: '💵', label: 'Tạm ứng / 전도금' },
    { cat: '관리 / Quản lý' },
    { id: 'vendors', icon: '🏢', label: 'NCC / 업체관리' },
    { id: 'device_mgmt', icon: '📱', label: 'Thiết bị / 기기관리' },
    { id: 'sys_settings', icon: '⚙️', label: 'Cài đặt / 시스템 설정' },
    { cat: '기타 / Khác' },
    { id: 'legal_forms', icon: '📄', label: 'Biểu mẫu / 법정서식' },
    { id: 'history', icon: '📆', label: 'Lịch sử / 이력' },
    { id: 'gallery', icon: '📸', label: 'Ảnh CT / 현장사진' },
  ],
  ceo: [
    { id: 'home', icon: '🏠', label: 'Trang chủ / 홈' },
    { id: 'multi_site', icon: '🌐', label: 'Tất cả CT / 전체 현장' },
    { cat: '근태 / Chấm công' },
    { id: 'attendance', icon: '⏰', label: 'Chấm công / 출퇴근' },
    { id: 'attendance_all', icon: '📊', label: 'QL chấm công / 근태관리' },
    { id: 'leave_all', icon: '🏖️', label: 'Nghỉ phép / 휴가' },
    { id: 'salary', icon: '💰', label: 'Bảng lương / 급여' },
    { cat: '현장 / Công trường' },
    { id: 'dashboard_all', icon: '🏛️', label: 'Tổng quan / 대시보드' },
    { id: 'safety', icon: '🛡️', label: 'An toàn / 안전점검' },
    { id: 'schedule', icon: '📅', label: 'Tiến độ / 공정' },
    { id: 'site_calendar', icon: '🗓️', label: 'Lịch trình / 일정관리' },
    { id: 'addwork', icon: '➕', label: 'Phát sinh / 추가항목' },
    { cat: '자재·장비 / Vật tư' },
    { id: 'equipment', icon: '🚜', label: 'Thiết bị / 장비·공구' },
    { id: 'material', icon: '📦', label: 'Vật tư / 자재관리' },
    { cat: '재무·기성 / Tài chính' },
    { id: 'quantities', icon: '📐', label: 'Khối lượng HĐ / 계약물량' },
    { id: 'labor', icon: '👷', label: 'Đơn giá NC / 인건비' },
    { id: 'costana', icon: '💹', label: 'Dòng tiền / 자금현황' },
    { id: 'expense_all', icon: '💸', label: 'Chi phí / 비용관리' },
    { id: 'billing_all', icon: '🧾', label: 'Nghiệm thu / 기성관리' },
    { id: 'advance', icon: '💵', label: 'Tạm ứng / 전도금' },
    { id: 'billing_status', icon: '📑', label: 'Nghiệm thu TĐ / 기성현황' },
    { id: 'accounting', icon: '📊', label: 'Kế toán / 회계' },
    { id: 'ceo_paid', icon: '✅', label: 'Duyệt chi / 지급결의' },
    { cat: '인력관리 / Nhân sự' },
    { id: 'workers', icon: '👷', label: 'Ho so CN / 인력 마스터' },
    { id: 'staff_all', icon: '👥', label: 'Nhân sự / 인력관리' },
    { id: 'roll_call', icon: '✅', label: 'Điểm danh / 출석체크' },
    { cat: '관리 / Quản lý' },
    { id: 'announcements', icon: '📢', label: 'Thông báo / 공지사항' },
    { id: 'daily_brief', icon: '📰', label: 'Tóm tắt / 일일브리핑' },
    { id: 'alert_center', icon: '🔔', label: 'Thông báo / 알림센터' },
    { id: 'defects', icon: '🔧', label: 'Bảo hành / 하자보수' },
    { id: 'estimator', icon: '🧮', label: 'Dự toán / 견적계산기' },
    { id: 'subcontract', icon: '🤝', label: 'Thầu phụ / 하도급정산' },
    { id: 'contracts', icon: '📑', label: 'Hợp đồng / 근로계약' },
    { id: 'vendors', icon: '🏢', label: 'NCC / 업체관리' },
    { id: 'doc_expiry', icon: '📄', label: 'Hết hạn / 문서만료' },
    { id: 'vehicle', icon: '🚗', label: 'Xe cộ / 차량현황' },
    { id: 'monthly_close', icon: '📅', label: 'Chốt tháng / 월마감' },
    { id: 'annual_report', icon: '📈', label: 'Báo cáo năm / 연간보고' },
    { id: 'sys_settings', icon: '⚙️', label: 'Cài đặt / 시스템 설정' },
    { id: 'client_portal', icon: '🔗', label: 'Chia sẻ / 고객포털' },
    { id: 'legal_forms', icon: '📄', label: 'Biểu mẫu / 법정서식' },
    { id: 'history', icon: '📆', label: 'Lịch sử / 이력' },
    { id: 'gallery', icon: '📸', label: 'Ảnh CT / 현장사진' },
    { cat: '🔒 대표 전용 / Giám đốc' },
    { id: 'security_all', icon: '🛡️', label: 'Bảo mật / 보안관리' },
    { id: 'gps_verify', icon: '📍', label: 'GPS xác minh / GPS검증' },
    { id: 'login_photos', icon: '📷', label: 'Ảnh đăng nhập / 로그인사진' },
  ],
}
